# Generated by Django 5.0.4 on 2024-04-24 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_XML_path', models.TextField(blank=True, max_length=3000)),
                ('new_XML_path', models.TextField(blank=True, max_length=3000)),
                ('old_XML_content', models.TextField(blank=True, max_length=300000)),
                ('new_XML_content', models.TextField(blank=True, max_length=300000)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modidied', models.DateTimeField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
