# Generated by Django 5.0.4 on 2024-04-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FetcherApp', '0003_openededitor_new_xml_path_openededitor_old_xml_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openededitor',
            name='XMLs_editor_data',
            field=models.TextField(blank=True, max_length=3000000),
        ),
    ]
