# Generated by Django 5.0.4 on 2024-04-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FetcherApp', '0004_alter_openededitor_xmls_editor_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openededitor',
            old_name='datetime_modidied',
            new_name='datetime_modified',
        ),
    ]
